
# Customize your settings and add new ones here
Host: "instilledbee.net"

LinkRoot: "/blog"
LinkHideExtensions: "true"
LinksUseHttps: true

SiteTitle: "The Ultimate Nerd"
SiteDescription: "InstilledBee's Programming Archive"
CaseInsensitiveTags: true
IndexFullPosts: false

CleanOutputPath: true

CommentEngine: "giscus"
GiscusRepoName: "instilledbee/the-ultimate-nerd"
GiscusRepoId: "MDEwOlJlcG9zaXRvcnkxNDY0NjUyNDU="
GiscusCategoryId: "DIC_kwDOCLrh3c4CnbNU"