on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to website
    runs-on: ubuntu-latest
    steps:
      - name: Install .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 6.0.x
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Statiq
        run: dotnet run
      - name: Clean target directory
        uses: taylorgibb/ftp-clean@v2.0.3
        with:
          host: ${{ secrets.FTP_HOST }}
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
      - name: Upload to FTP
        uses: anvil-solutions/Fast-FTP-Action@2.1.3
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          method: sftp
          local_dir: /output
          remote_dir: ${{ secrets.FTP_PATH }}
