name: Live Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to website
    runs-on: ubuntu-latest
    steps:
      - name: Install .NET
        uses: actions/setup-dotnet@v6.0.0
        with:
          dotnet-version: 10.x
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Run Statiq
        run: dotnet run
      - name: Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          method: ftp
          local-dir: ./output/
          server-dir: ${{ secrets.FTP_PATH }}
