name: Live Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to website
    runs-on: ubuntu-latest
    steps:
      - name: Install .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 7.x
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run Statiq
        run: dotnet run
      - name: Upload to FTP
        uses: anvil-solutions/Fast-FTP-Action@2.1.3
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          method: ftp
          local_dir: ./output
          remote_dir: ${{ secrets.FTP_PATH }}
